name: node-auth-svc

on:
  push:
    branches:
      - main
      - feature/initial-commit
    paths:
      - .github/workflows/node-auth-svc.yml

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
      TEST_MONGO_URL: ${{ secrets.TEST_MONGO_URL }}
    services:
      redis-server:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - run: npm ci

      - run: npm run test
